name: dockerbuild

on:
  workflow_run:
    workflows: ["test"]
    types:
      - completed

jobs:
  dockerbuild:
    if: false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true  # Set to false if you don't want to push the image
        tags: your-dockerhub-username/hello-go:latest

